title: Another Iteration
email: alex.bird@hunterindustries.com
description: >-
  Notes from the Hunter Software Department
baseurl: "/blog"
url: "https://alexbird-hunterindustries.github.io/"
icon: /assets/images/icon-512.png
favicon: /assets/images/favicon.ico
github_username:  alexbird-hunterindustries

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num/"
