title: The Cannery
email: alex.bird@hunterindustries.com
description: >-
  Preserving what we learn in the Hunter Software Department
baseurl: "/blog"
url: "https://alexbird-hunterindustries.github.io/"
icon: /assets/images/icon-512.png
icon_svg: /assets/images/icon.svg
icon_svg_reverse: /assets/images/icon-reverse.svg
favicon: /assets/images/favicon.ico
github_username:  alexbird-hunterindustries

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num/"
