trigger:
  branches:
    include:
      - main

stages:
  - stage: deployToS3
    jobs:
    - job: DeployToS3
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: UseRubyVersion@0
          inputs:
            versionSpec: '>= 2.5'

        - displayName: 'bundle install'
          script: |
            gem install bundler
            bundle install --retry=3 --jobs=4
         
        - displayName: 'jekyll build'
          script: |
            bundle exec jekyll build
