trigger:
  branches:
    include:
      - main

stages:
  - stage: deployToS3
    variables:
      - group: aws-s3-deployment-credentials-for-hunter-software-blog
    jobs:
    - job: DeployToS3
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: UseRubyVersion@0
          inputs:
            versionSpec: '>= 2.5'
        - script: |
            gem install bundler
            bundle install --retry=3 --jobs=4

          displayName: 'bundle install'
         
        - script: |
            bundle exec jekyll build
          
          displayName: 'jekyll build'

        - script: |
            ls
            ls _site
            echo somehow upload to $(BUCKET_NAME) in $(AWS_REGION)
          displayName: Upload to S3
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_REGION)
